### ISSUE TITLE
Why doesn't this repo make mysql faster than torndb?

### ISSUE THREAD

**Issue by dantangfan** [PyMySQL/Tornado-MySQL#25]
My test code just like this

```

#!/usr/bin/env python
# -*-coding:utf-8-*-

import sys
reload(sys)
sys.setdefaultencoding("utf-8")

import torndb
import tornado.web
import tornado.httpserver
import tornado.ioloop
import tornado.options
from tornado.gen import coroutine, sleep
from tornado.options import options, define

from tornado_mysql.pools import Pool

define("port", type=int, default=8888)
options.parse_command_line()

sync_conn = torndb.Connection(host="localhost:3306", user="xxx", password="xxx", database="xxx")
POOL = Pool(
    dict(host='127.0.0.1', port=3306, user='xxx', passwd='xxx', db='xxx'),
    max_idle_connections=100,)

class TorndbHandler(tornado.web.RequestHandler):
    @coroutine
    def get(self):
        sql = "select * from user"
        res = sync_conn.query(sql)
        return


class PoolHandler(tornado.web.RequestHandler):
    @coroutine
    def get(self):
        sql = "select * from user"
        res = yield POOL.execute(sql)
        res.fetchall()
        return

if __name__ == "__main__":
    settings = {
        'debug': True
    }
    app = tornado.web.Application(
        handlers=[
            (r'/torndb', TorndbHandler),
            (r'/asyncpooldb', PoolHandler),
        ],
        **settings
        )
    tornado.httpserver.HTTPServer(app).listen(options.port)
    loop = tornado.ioloop.IOLoop.instance()
    loop.start()

```

and i use ab test, the result like this : 

```
>>ab -c 10 -n 40 http://127.0.0.1:8888/torndb

Concurrency Level:      10
Time taken for tests:   0.680 seconds
Complete requests:      40
Failed requests:        0
Total transferred:      7760 bytes
HTML transferred:       0 bytes
Requests per second:    58.84 [#/sec] (mean)
Time per request:       169.963 [ms] (mean)
Time per request:       16.996 [ms] (mean, across all concurrent requests)
Transfer rate:          11.15 [Kbytes/sec] received

Connection Times (ms)
              min  mean[+/-sd] median   max
Connect:        0    0   0.1      0       0
Processing:    16  148  93.1    148     679
Waiting:       16  148  93.1    148     679
Total:         16  148  93.1    149     680
```

```
>>ab -c 10 -n 40 http://127.0.0.1:8888/asyncpooldb

Concurrency Level:      10
Time taken for tests:   1.605 seconds
Complete requests:      40
Failed requests:        0
Total transferred:      7760 bytes
HTML transferred:       0 bytes
Requests per second:    24.91 [#/sec] (mean)
Time per request:       401.371 [ms] (mean)
Time per request:       40.137 [ms] (mean, across all concurrent requests)
Transfer rate:          4.72 [Kbytes/sec] received

Connection Times (ms)
              min  mean[+/-sd] median   max
Connect:        0    0   0.1      0       1
Processing:   389  401   9.2    405     413
Waiting:      389  401   9.2    405     413
Total:        389  401   9.3    406     413
```

The mysql user table has hundreds of lines.

The result shows that torndb is faster than this repo. Is this correct? Why? Shouldn't async be faster?

Best Regards,

**Comment by methane** [comment]
In general, async is slower. Especially on Python.
* async operation makes a lot of function call. function call is very slow on Python.
* Writing fast C extension is more difficult than blocking.

When comparing memory consumption under massive (and slow) concurrency,
async code consumes less memory than blocking code.  Since thread uses stack memory.

See also: http://techspot.zzzeek.org/2015/02/15/asynchronous-python-and-databases/

**Comment by dantangfan** [comment]
WOW !! Great post!
So, in my single thread tornado server,  there is no need to use this async-mysql. It'll not increase in performance under massive (and slow) concurrency.

But without any increase performance, when should i use async-mysql ?

**Comment by methane** [comment]
When you want to measure performance difference between threadpool vs async. :)

**Comment by bazzilic** [comment]
If you want to serve more than one user at a time with your tornado server, it makes sense to use an async database driver. Otherwise if you have relatively long-running queries to the db, the request handler will be blocked until it gets the result from the db and no other requests would be processed at the time.

**Comment by methane** [comment]
@bazzilic threadpool can be used for concurrency.
In case of redis, subscribing pubsub channel is good example to use async client.
Redis is optimized for massive concurrent client and subscribing pubsub channel may be blocked for long time.

But in case of MySQL, I don't know good real example to use async client,
since MySQL server is not optimized for massive concurrent connections.

**Comment by dantangfan** [comment]
@methane get it! Then, how about async memcached/redis cache?

**Comment by methane** [comment]
Memcached is stateless (transaction-less) and supports pipelining.
So fastest way is pipelining + multiplexing.  You can use only one connection for concurrent requests.
It reduces packets/sec and server-side CPU usage.

In case of redis, most queries except pubsub are same to memcached.
When using pubsub, Tornado-Redis may help you.

**Comment by dantangfan** [comment]
Oo⚬h, thanks a lot!
